services:

   #VIEW          
    listener.view:
        class: App\EventListener\ViewListener
        arguments: ['@translator.default', '@manager.logger']
        #, '@manager.logger']
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
        #VIEW

    listener.validator:
        class: App\EventListener\ParameterValidatorListener
        arguments: ['@annotation_reader', '@validator', '@doctrine' ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelRequest }

    manager.logger:
        class: App\Manager\LoggerManager
        arguments: ['@doctrine.orm.entity_manager','@request_stack', 'true' ]#,  '@logger.ws'
        public: false



    App\Manager\FileManager:
        public: true
        class: App\Manager\FileManager
        arguments: [ '@doctrine.orm.entity_manager', '%uploads_directory%' , '@App\Manager\FolderManager']
        
    App\Manager\FolderManager:
        public: true
        class: App\Manager\FolderManager
        arguments: [ '@doctrine.orm.entity_manager' ]

    App\Manager\DashboardManager:
        public: true
        class: App\Manager\DashboardManager
        arguments: [ '@doctrine.orm.entity_manager' ]
