services:

   #VIEW          
    listener.view:
        class: App\EventListener\ViewListener
        arguments: ['@translator.default']
        #, '@manager.logger']
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
     
    listener.validator:
        class: App\EventListener\ParameterValidatorListener
        arguments: ['@annotation_reader', '@validator', '@doctrine' ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelRequest }


    App\Manager\FileManager:
        public: true
        class: App\Manager\FileManager
        arguments: [ '@doctrine.orm.entity_manager', '%uploads_directory%' , '@App\Manager\FolderManager']
        
    App\Manager\FolderManager:
        public: true
        class: App\Manager\FolderManager
        arguments: [ '@doctrine.orm.entity_manager' ]

    App\Manager\DashboardManager:
        public: true
        class: App\Manager\DashboardManager
        arguments: [ '@doctrine.orm.entity_manager' ]
